version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:8082"
    environment:
      POSTGRES_DB: ${AUTH_DATABASE}
      POSTGRES_USER: ${AUTH_USER}
      POSTGRES_PASSWORD: ${AUTH_PASSWORD}

  book-storage-service:
    build:
      context: ./book-storage-service
    ports:
      - "${BOOK_STORAGE_SERVICE_PORT}:8081"
    environment:
      POSTGRES_DB: ${BOOK_STORAGE_DATABASE}
      POSTGRES_USER: ${BOOK_STORAGE_USER}
      POSTGRES_PASSWORD: ${BOOK_STORAGE_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  book-tracker-service:
    build:
      context: ./book-tracker-service
    ports:
      - "${BOOK_TRACKER_SERVICE_PORT}:8083"
    environment:
      POSTGRES_DB: ${BOOK_TRACKER_DATABASE}
      POSTGRES_USER: ${BOOK_TRACKER_USER}
      POSTGRES_PASSWORD: ${BOOK_TRACKER_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  postgres-auth:
    container_name: users_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_DATABASE}
      POSTGRES_USER: ${AUTH_USER}
      POSTGRES_PASSWORD: ${AUTH_PASSWORD}
    ports:
      - "${POSTGRES_LOCAL_PORT_AUTH}:5432"

  postgres-book-storage:
    container_name: book_storage_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${BOOK_STORAGE_DATABASE}
      POSTGRES_USER: ${BOOK_STORAGE_USER}
      POSTGRES_PASSWORD: ${BOOK_STORAGE_PASSWORD}
    ports:
      - "${POSTGRES_LOCAL_PORT_STORAGE}:5432"

  postgres-book-tracker:
    container_name: book_tracker_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${BOOK_TRACKER_DATABASE}
      POSTGRES_USER: ${BOOK_TRACKER_USER}
      POSTGRES_PASSWORD: ${BOOK_TRACKER_PASSWORD}
    ports:
      - "${POSTGRES_LOCAL_PORT_TRACKER}:5432"
