version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  #  auth-service:
  #    build:
  #      context: ./auth-service
  #    ports:
  #      - "${AUTH_SERVICE_PORT}:8082"
  #    environment:
  #      POSTGRES_DB: ${AUTH_DATABASE}
  #      POSTGRES_USER: ${AUTH_USER}
  #      POSTGRES_PASSWORD: ${AUTH_PASSWORD}
  #
  #  book-storage-service:
  #    build:
  #      context: ./book-storage-service
  #    ports:
  #      - "${BOOK_STORAGE_SERVICE_PORT}:8081"
  #    environment:
  #      POSTGRES_DB: ${BOOK_STORAGE_DATABASE}
  #      POSTGRES_USER: ${BOOK_STORAGE_USER}
  #      POSTGRES_PASSWORD: ${BOOK_STORAGE_PASSWORD}
  #      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #
  #  book-tracker-service:
  #    build:
  #      context: ./book-tracker-service
  #    ports:
  #      - "${BOOK_TRACKER_SERVICE_PORT}:8083"
  #    environment:
  #      POSTGRES_DB: ${BOOK_TRACKER_DATABASE}
  #      POSTGRES_USER: ${BOOK_TRACKER_USER}
  #      POSTGRES_PASSWORD: ${BOOK_TRACKER_PASSWORD}
  #      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  postgres-auth:
    container_name: users_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_DATABASE}
      POSTGRES_USER: ${AUTH_USER}
      POSTGRES_PASSWORD: ${AUTH_PASSWORD}
    ports:
      - ${POSTGRES_LOCAL_PORT_AUTH}:5432

  postgres-book-storage:
    container_name: book_storage_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${BOOK_STORAGE_DATABASE}
      POSTGRES_USER: ${BOOK_STORAGE_USER}
      POSTGRES_PASSWORD: ${BOOK_STORAGE_PASSWORD}
    ports:
      - ${POSTGRES_LOCAL_PORT_STORAGE}:5432

  postgres-book-tracker:
    container_name: book_tracker_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${BOOK_TRACKER_DATABASE}
      POSTGRES_USER: ${BOOK_TRACKER_USER}
      POSTGRES_PASSWORD: ${BOOK_TRACKER_PASSWORD}
    ports:
      - ${POSTGRES_LOCAL_PORT_TRACKER}:5432
