server:
  port: 8083
spring:
  application:
    name: book-tracker-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5446/book_tracker_db
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.LongDeserializer
springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


books:
  default-return-days: 5
