spring:
  application:
    name: book-storage-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5444/book_storage_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  server:
    port: 8081
